#云编译公用核心
name: WRT-CORE

on:
  workflow_call:
    inputs:
      WRT_CONFIG:
        required: true
        type: string
      WRT_THEME:
        required: true
        type: string
      WRT_NAME:
        required: true
        type: string
      WRT_SSID:
        required: true
        type: string
      WRT_WORD:
        required: true
        type: string
      WRT_IP:
        required: true
        type: string
      WRT_PW:
        required: true
        type: string
      WRT_REPO:
        required: true
        type: string
      WRT_BRANCH:
        required: true
        type: string
      WRT_SOURCE:
        required: false
        type: string
      WRT_PACKAGE:
        required: false
        type: string
      WRT_TEST:
        required: false
        type: string
      CI_NAME:
        required: false
        type: string
      WRT_ARCH:
        required: false
        type: string
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  WRT_CONFIG: ${{inputs.WRT_CONFIG}}
  WRT_THEME: ${{inputs.WRT_THEME}}
  WRT_NAME: ${{inputs.WRT_NAME}}
  WRT_SSID: ${{inputs.WRT_SSID}}
  WRT_WORD: ${{inputs.WRT_WORD}}
  WRT_IP: ${{inputs.WRT_IP}}
  WRT_PW: ${{inputs.WRT_PW}}
  WRT_REPO: ${{inputs.WRT_REPO}}
  WRT_BRANCH: ${{inputs.WRT_BRANCH}}
  WRT_PACKAGE: ${{inputs.WRT_PACKAGE}}
  WRT_TEST: ${{inputs.WRT_TEST}}
  WRT_DIR: 'wrt'
  CI_NAME: ${{inputs.CI_NAME}}
  WRT_ARCH: ${{inputs.WRT_ARCH}}

jobs:
  core:
    name: ${{inputs.WRT_SOURCE}}
    runs-on: ubuntu-latest
    steps:
      - name: Install BC
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -yqq install bc

      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/share/chromium /usr/local/share/powershell"
          testing: false

      - name: Checkout Projects
        uses: actions/checkout@main
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -yqq purge firefox
          sudo -E apt -yqq update
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E apt -yqq install dos2unix python3-netifaces libfuse-dev
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"
#          sudo chown $USER:$GROUPS $GITHUB_WORKSPACE
#          sudo mkdir -p /mnt/build_wrt
#          sudo chown $USER:$USER /mnt/build_wrt
#          sudo ln -s /mnt/build_wrt $GITHUB_WORKSPACE/wrt

      - name: Initialization Values
        run: |
          echo "WRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
          echo "WRT_MARK=${GITHUB_REPOSITORY%%/*}" >> $GITHUB_ENV
          echo "WRT_INFO=${WRT_SOURCE%%/*}" >> $GITHUB_ENV
          echo "WRT_TARGET=$(grep -m 1 -oP '^CONFIG_TARGET_\K[\w]+(?=\=y)' ./Config/$WRT_CONFIG.txt)" >> $GITHUB_ENV
          echo "WRT_KVER=none" >> $GITHUB_ENV
          echo "WRT_LIST=none" >> $GITHUB_ENV

          echo "WRT_CI=$WRT_CI" >> $GITHUB_ENV
          [[ -z $WRT_ARCH ]] && {
            export WRT_ARCH=$(sed -n 's/.*_DEVICE_\(.*\)_DEVICE_.*/\1/p' $GITHUB_WORKSPACE/Config/$WRT_CONFIG.txt | head -n 1)
            echo "WRT_ARCH=$WRT_ARCH" >> $GITHUB_ENV
          }
          echo "$WRT_REPO/$WRT_BRANCH" > "$GITHUB_WORKSPACE/repo_flag"
      - name: Clone Code
        run: |
          git clone --depth=1 --single-branch --branch $WRT_BRANCH $WRT_REPO ./wrt/

          cd ./wrt/ && echo "WRT_HASH=$(git log -1 --pretty=format:'%h')" >> $GITHUB_ENV

      - name: Check Scripts
        run: |
          find ./ -maxdepth 3 -type f -iregex ".*\(txt\|sh\)$" -exec dos2unix {} \; -exec chmod +x {} \;

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./wrt/.ccache
            ./wrt/staging_dir
          key: ${{ env.WRT_ARCH }}-${{ hashFiles('**/repo_flag') }}-${{ env.WRT_DATE }}
          restore-keys: |
            ${{ env.WRT_ARCH }}-${{ hashFiles('**/repo_flag') }}-

      - name: Refresh the cache
        run: |
          if [ -d "./wrt/staging_dir" ]; then
            find "./wrt/staging_dir" -type d -name "stamp" -not -path "*target*" | while read -r dir; do
                find "$dir" -type f -exec touch {} +
            done
          fi            



      - name: Update Feeds
        run: |
          cd ./wrt/

          if ! grep -q '^src-git fantastic_packages ' feeds.conf.default; then
            echo 'src-git fantastic_packages https://github.com/fantastic-packages/packages.git;master' >> feeds.conf.default
          fi
          grep 'fantastic_packages' feeds.conf.default

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom Packages
        run: |
          cd ./wrt/package/

          $GITHUB_WORKSPACE/Scripts/Packages.sh
          $GITHUB_WORKSPACE/Scripts/Handles.sh

      - name: Custom Settings
        run: |
          . $GITHUB_WORKSPACE/Scripts/function.sh
          cd ./wrt/
          
          generate_config

          echo "WRT_FILES=$WRT_FILES" >> $GITHUB_ENV

          [ -f "$WRT_FILES" ] && cp -Rf $WRT_FILES files
          [ -f "$GITHUB_WORKSPACE/Config/$WRT_CONFIG.txt" ] && cat "$GITHUB_WORKSPACE/Config/$WRT_CONFIG.txt" > .config
          [ -n "$WRT_PACKAGE" ] && { 
            echo "$WRT_PACKAGE" | tr ',' '\n' | while read -r package; do 
              sed -i "/$package/d" .config
              echo -e "CONFIG_PACKAGE_$package=y" >> .config
            done
          }
          
          echo "CONFIG_TARGET_OPTIONS=y" >> .config
          grep -v '^#' .config | grep -v '^$'
          
          chmod +x $GITHUB_WORKSPACE/Scripts/Settings.sh
          $GITHUB_WORKSPACE/Scripts/Settings.sh
          source ./.config
          make defconfig

          echo "WRT_FILES=$WRT_FILES" >> $GITHUB_ENV
          
          if [ -f ./package/kernel/linux/files/Makefile ]; then
            export WRT_KVER=$(grep -oP '^KERNEL_PATCHVER:=\K[\d.]+' ./package/kernel/linux/files/Makefile | head -n 1)
          else
            export WRT_KVER=$(grep -oP '^KERNEL_PATCHVER:=\K[\d.]+' ./target/linux/$WRT_TARGET/Makefile | head -n 1)
          fi
          [ -z "$WRT_KVER" ] && export WRT_KVER=none
          echo "WRT_KVER=$WRT_KVER" >> $GITHUB_ENV

      - name: Download DL Package
        run: |
          cd ./wrt/
          make defconfig
          make download -j8
          
          find ./dl/ -size -1024c -exec ls -l {} \;
          find ./dl/ -size -1024c -exec rm -f {} \;
          
      - name: Compile Firmware
        id: compile
        run: |
          cd ./wrt/
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Organize Artifacts
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cd ./wrt/bin/targets/*/*

          [ -d packages ] && { 
            PACKAGES_DIR=$(find packages -type f -name '*.apk' | xargs -r ls -S | head -n 1)
            [ -n "$PACKAGES_DIR" ] && PACKAGES_DIR=$(dirname "$PACKAGES_DIR") || PACKAGES_DIR=packages
            mv "$PACKAGES_DIR" ../../../packages
          }
          
          rm -rf packages *.buildinfo *.json sha256sums seed
          echo "WRT_PATH=$PWD" >> $GITHUB_ENV
          
      - name: Upload Firmware To Artifact
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          name: ${{env.WRT_DATE}}_firmware
          path: ${{env.WRT_PATH}}
          retention-days: 2

      - name: Upload Packages To Artifact
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          name: ${{env.WRT_DATE}}_packages
          path: ./wrt/bin/packages/
          retention-days: 2

      - name: Upload Packages To Release
        uses: softprops/action-gh-release@master
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          files: ./wrt/bin/packages/**/*.apk
          tag_name: ${{ env.WRT_DATE }}
          append_body: true
          body: |
            - 软件包仅供测试
            - 默认密码：password
            - 默认地址：${{ env.WRT_IP }}
            - 默认后台：[http://${{ env.WRT_IP }}](http://${{ env.WRT_IP }})
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Organize Release
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          if [ -z "${{ env.WRT_FILES }}" ]; then
              echo "WRT_TAG=${{ env.WRT_MARK }}-${{ env.WRT_DATE }}" >> $GITHUB_ENV
          else
              echo "WRT_TAG=${{ env.WRT_MARK }}-${{ env.WRT_CONFIG }}_${{ env.WRT_DATE }}" >> $GITHUB_ENV
          fi
          
          echo "WRT_RELEASE=$WRT_TAG $WRT_THEME" >> $GITHUB_ENV
          echo "WRT_RELEASE=$WRT_RELEASE, LuCI Version $(grep -Po '(?<=DISTRIB_REVISION=).*' $WRT_PATH/../../../etc/openwrt_release | tr -d "'") by $GITHUB_ACTOR" >> $GITHUB_ENV
          
          cat > release.txt <<EOF
          当前使用源码: ${{ env.WRT_SOURCE }}
          当前编译时间: ${{ env.WRT_DATE }}
          当前默认后台: [http://${{ env.WRT_IP }}](http://${{ env.WRT_IP }})
          当前默认密码: password
          LuCI版本: $(grep -Po '(?<=DISTRIB_REVISION=).*' $WRT_PATH/../../../etc/openwrt_release | tr -d "'")
          编译使用设置: [${{ env.CI_NAME }}](https://github.com/${{ github.repository }}/tree/main/Config)
          EOF

      - name: Upload Firmware To Release
        uses: softprops/action-gh-release@master
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          files: ${{ env.WRT_PATH }}/*
          name: ${{ env.WRT_RELEASE }}
          tag_name: ${{ env.WRT_TAG }}
          body_path: release.txt
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Telegram notification
        continue-on-error: true
        if: steps.compile.outputs.status == 'success' && !cancelled() && env.TELEGRAM_BOT_TOKEN != null && env.TELEGRAM_CHAT_ID != null
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
               -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
               -d "text=OpenWrt 固件编译完成！%0A仓库: ${{ github.repository }}%0ATag: ${{ env.WRT_TAG }}%0A时间: ${{ env.WRT_DATE }}"
